AWSTemplateFormatVersion: 2010-09-09
Description: This script creates a cluster whit ec2 instances
    
Parameters: 
    Ami:
      Type: String

    EC2InstanceType:
      Type: String
    
    EC2SecurityGroup:
      Type: String
    
    ClusterSize:
      Type: Number
    
    ListSubnets:
        Type: CommaDelimitedList
    
    EnvironmentName:
        Type: String

Resources:
    ECSCluster:
      Type: "AWS::ECS::Cluster"
      Properties:
          ClusterName: !Sub ${EnvironmentName}-cluster
    
    ECSAutoScalingGroup:
      Type: "AWS::AutoScaling::AutoScalingGroup"
      DependsOn: ECSCluster
      Properties:
          AutoScalingGroupName: !Sub ${EnvironmentName}-ASGN
          DesiredCapacity: !Ref ClusterSize
          LaunchConfigurationName: !Ref ECSLaunchConfiguration
          MaxSize: !Ref ClusterSize  #required
          MinSize: !Ref ClusterSize #required
          VPCZoneIdentifier: !Ref ListSubnets
          
    ECSLaunchConfiguration:
      Type: "AWS::AutoScaling::LaunchConfiguration"
      Properties:
          ImageId: !Ref Ami #required
          InstanceType: !Ref EC2InstanceType #required
          IamInstanceProfile: !Ref ECSInstanceProfile
          SecurityGroups: 
              - !Ref EC2SecurityGroup
          UserData:
              Fn::Base64: 
                  !Sub |
                  #!/bin/bash
                  echo ECS_CLUSTER=${EnvironmentName}-cluster >> /etc/ecs/ecs.config

# IAM Role por ecs agent
# https://docs.aws.amazon.com/AmazonECS/latest/developerguide/instance_IAM_role.html  
    
    ECSRole:
      Type: "AWS::IAM::Role"
      Properties:
        Path: /
        RoleName: !Sub ${EnvironmentName}-ECSRole-${AWS::Region}
        AssumeRolePolicyDocument: |
          {
              "Statement": [{
                  "Action": "sts:AssumeRole",
                  "Effect": "Allow",
                  "Principal": {
                      "Service": "ec2.amazonaws.com"
                  }
              }]
          }
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
        Policies:
          - PolicyName: ecs-service
            PolicyDocument: |
              {
                  "Statement": [{
                      "Effect": "Allow",
                      "Action": [
                          "ecs:CreateCluster",
                          "ecs:DeregisterContainerInstance",
                          "ecs:DiscoverPollEndpoint",
                          "ecs:Poll",
                          "ecs:RegisterContainerInstance",
                          "ecs:StartTelemetrySession",
                          "ecs:Submit*",
                          "ecr:BatchCheckLayerAvailability",
                          "ecr:BatchGetImage",
                          "ecr:GetDownloadUrlForLayer",
                          "ecr:GetAuthorizationToken"
                      ],
                      "Resource": "*"
                  }]
              }

    ECSInstanceProfile:
      Type: AWS::IAM::InstanceProfile
      Properties:
        Path: /
        Roles:
          - !Ref ECSRole
                  
Outputs:
  ECSCluster:
    Description: A reference to the created Cluster
    Value: !Ref ECSCluster


    

  

